const loadLib = path => require(`../../node_modules/antd/lib/${path}/index`)

export default {
  Affix: loadLib('affix'),
  Datepicker: loadLib('datepicker'),
  Tooltip: loadLib('tooltip'),
  Carousel: loadLib('carousel'),
  Tabs: loadLib('tabs'),
  Modal: loadLib('modal'),
  Dropdown: loadLib('dropdown'),
  Progress: loadLib('progress'),
  Popover: loadLib('popover'),
  Select: loadLib('select'),
  Breadcrumb: loadLib('breadcrumb'),
  Popconfirm: loadLib('popconfirm'),
  Pagination: loadLib('pagination'),
  Steps: loadLib('steps'),
  InputNumber: loadLib('input-number'),
  Switch: loadLib('switch'),
  Checkbox: loadLib('checkbox'),
  Table: loadLib('table'),
  Tag: loadLib('tag'),
  Collapse: loadLib('collapse'),
  message: loadLib('message'),
  Slider: loadLib('slider'),
  QueueAnim: loadLib('queue-anim'),
  Radio: loadLib('radio'),
  notification: loadLib('notification'),
  Alert: loadLib('alert'),
  Validation: loadLib('validation'),
  Tree: loadLib('tree'),
  Upload: loadLib('upload'),
  Badge: loadLib('badge'),
  Menu: loadLib('menu'),
  Timeline: loadLib('timeline'),
  Button: loadLib('button'),
  Icon: loadLib('icon'),
  Row: loadLib('row'),
  Col: loadLib('col'),
  Spin: loadLib('spin'),
  Form: loadLib('form'),
  Input: loadLib('input'),
  Calendar: loadLib('calendar'),
  Timepicker: loadLib('timepicker')
}
